# Generated by Django 5.2.1 on 2025-06-05 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='total_courses',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='total_students',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursesupervisorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentmanagerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CollegeManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
