# Generated by Django 5.2.1 on 2025-06-07 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_lecturerprofile_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegemanagerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coursesupervisorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='departmentmanagerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='CollegeManagerProfile',
        ),
        migrations.DeleteModel(
            name='CourseSupervisorProfile',
        ),
        migrations.DeleteModel(
            name='DepartmentManagerProfile',
        ),
    ]
