# Generated by Django 5.2.1 on 2025-06-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_collegemanagerprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='available_for_consulting',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='major',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', to='profiles.language'),
        ),
    ]
