# Generated by Django 5.2.1 on 2025-06-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_college_college_admin'),
        ('courses', '0002_remove_course_program_course_department_and_more'),
        ('department', '0003_alter_department_description'),
        ('profiles', '0005_lecturerprofile_college_lecturerprofile_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_profiles', to='college.college'),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_profiles', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_profiles', to='department.department'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='college.college'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='department.department'),
        ),
    ]
