# Generated by Django 5.2.1 on 2025-06-09 12:13

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_college_is_active'),
        ('courses', '0004_course_is_active_lesson_is_active_lesson_slug_and_more'),
        ('department', '0006_department_admin'),
        ('profiles', '0006_alter_lecturerprofile_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='college',
            field=models.ManyToManyField(blank=True, related_name='lecturer_profiles', to='college.college'),
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='lecturer_profiles', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='lecturer_profiles', to='department.department'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', to='courses.course'),
        ),
    ]
