# Generated by Django 5.2.1 on 2025-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_lecturerprofile_address_lecturerprofile_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturerprofile',
            old_name='college',
            new_name='colleges',
        ),
        migrations.RenameField(
            model_name='lecturerprofile',
            old_name='department',
            new_name='departments',
        ),
    ]
