# Generated by Django 5.2.1 on 2025-06-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_college_lecturerprofile_colleges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturerprofile',
            old_name='course',
            new_name='courses',
        ),
    ]
