# Generated by Django 5.2.1 on 2025-06-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
