# Generated by Django 5.1.6 on 2026-01-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=1000, null=True)),
                ('answer', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('about', models.TextField(blank=True, max_length=1000, null=True)),
                ('max_students', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='college_thumbnails/')),
                ('intro_video_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('targeted_audience', models.TextField(blank=True)),
                ('questions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.question')),
            ],
        ),
    ]
