# Generated by Django 5.2.1 on 2025-06-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
