# Generated by Django 5.2.1 on 2025-06-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_college_description_ar_college_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='college',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='college',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='college/images/'),
        ),
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='college/images/thumbnails/'),
        ),
    ]
