# Generated by Django 5.2.1 on 2025-06-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_college_college_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
