# Generated by Django 5.2.1 on 2025-07-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_college_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='college',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='college',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='college',
            name='name_en',
        ),
    ]
