# Generated by Django 5.2.1 on 2025-07-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_remove_college_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quasstion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=1000, null=True)),
                ('answer', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='college_admin',
        ),
        migrations.RemoveField(
            model_name='college',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='college',
            name='image',
        ),
        migrations.RemoveField(
            model_name='college',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='college',
            name='name',
        ),
        migrations.RemoveField(
            model_name='college',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='college',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='difficulty_level',
            field=models.CharField(choices=[('all', 'All Levels'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advance', 'Advance'), ('expert', 'Expert')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='intro_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='max_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='targeted_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='college_thumbnails/'),
        ),
        migrations.AddField(
            model_name='college',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.quasstion'),
        ),
    ]
