# Generated by Django 5.2.1 on 2025-07-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_quasstion_remove_college_college_admin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quasstion',
            new_name='Question',
        ),
    ]
