# Generated by Django 5.2.1 on 2025-07-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_rename_quasstion_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='difficulty_level',
        ),
    ]
