# Generated by Django 5.2.1 on 2025-05-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('lecturer', 'Lecturer'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='lecturer_profiles', to='accounts.language'),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='lecturer_profiles', to='accounts.skill'),
        ),
    ]
