# Generated by Django 5.2.1 on 2025-08-07 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_address_remove_user_city_and_more'),
        ('department', '0007_remove_department_degree_level_delete_degreelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
    ]
