# Generated by Django 5.2.1 on 2025-08-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainDashboard', '0002_department_remove_course_colleges_delete_college_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
