# Generated by Django 5.2.1 on 2025-06-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_college_is_active'),
        ('courses', '0002_remove_course_program_course_department_and_more'),
        ('department', '0003_alter_department_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='colleges',
            field=models.ManyToManyField(blank=True, related_name='courses', to='college.college', verbose_name='Colleges offering this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='courses', to='department.department', verbose_name='Departments offering this course'),
        ),
    ]
