# Generated by Django 5.2.1 on 2025-06-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_active_lesson_is_active_lesson_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
    ]
