# Generated by Django 5.2.1 on 2025-07-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_question_quiz_choice_question_quiz_review_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='departments',
        ),
    ]
