# Generated by Django 5.2.1 on 2025-08-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_review_rate'),
        ('department', '0007_remove_department_degree_level_delete_degreelevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='colleges',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='department.department'),
            preserve_default=False,
        ),
    ]
