# Generated by Django 5.2.1 on 2025-12-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub Title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='about/videos', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
