from HiStudyApp.views import homeViews, blogViews, pagesViews, coursesViews, dashboardViews, elementsViews, mainViews
from django.urls import path

urlpatterns = [
    path('', homeViews.mainDemo, name ='mainDemo'),
    path('art-design-school', homeViews.artDesignSchool, name ='artDesignSchool'),
    path('checkout', homeViews.checkout, name ='checkout'),
    path('classic-lms', homeViews.classicLms, name ='classicLms'),
    path('coaching', homeViews.coaching, name ='coaching'),
    path('course-school', homeViews.courseSchool, name ='courseSchool'),
    path('gym-coaching', homeViews.gymCoaching, name ='gymCoaching'),
    path('health-wellness-institute', homeViews.healthWellnessInstitute, name ='healthWellnessInstitute'),
    path('home-elegant', homeViews.homeElegant, name ='homeElegant'),
    path('home-technology', homeViews.homeTechnology, name ='homeTechnology'),
    path('instructor-course', homeViews.instructorCourse, name ='instructorCourse'),
    path('instructor-portfolio', homeViews.instructorPortfolio, name ='instructorPortfolio'),
    path('instructors-coaches', homeViews.instructorsCoaches, name ='instructorsCoaches'),
    path('islamic-center', homeViews.islamicCenter, name ='islamicCenter'),
    path('kindergarten', homeViews.kindergarten, name ='kindergarten'),
    path('language-academy', homeViews.languageAcademy, name ='languageAcademy'),
    path('life-coach', homeViews.lifeCoach, name ='lifeCoach'),
    path('main-demo', homeViews.mainDemo, name ='mainDemo'),
    path('marketplace', homeViews.marketplace, name ='marketplace'),
    path('modern-university', homeViews.modernUniversity, name ='modernUniversity'),
    path('multilingual', homeViews.multilingual, name ='multilingual'),
    path('online-academy', homeViews.onlineAcademy, name ='onlineAcademy'),
    path('online-course', homeViews.onlineCourse, name ='onlineCourse'),
    path('online-school', homeViews.onlineSchool, name ='onlineSchool'),
    path('single-course', homeViews.singleCourse, name ='singleCourse'),
    path('udemy-affiliate', homeViews.udemyAffiliate, name ='udemyAffiliate'),
    path('university-classic', homeViews.universityClassic, name ='universityClassic'),
    path('university-status', homeViews.universityStatus, name ='universityStatus'),
    path('wishlist', homeViews.wishlist, name ='wishlist'),

    # blog
    path('blog', blogViews.blog, name ='blog'),
    path('blog-details', blogViews.blogDetails, name ='blogDetails'),
    path('blog-grid-minimal', blogViews.blogGridMinimal, name ='blogGridMinimal'),
    path('blog-list', blogViews.blogList, name ='blogList'),
    path('blog-with-sidebar', blogViews.blogWithSidebar, name ='blogWithSidebar'),
    path('post-format-audio', blogViews.postFormatAudio, name ='postFormatAudio'),
    path('post-format-gallery', blogViews.postFormatGallery, name ='postFormatGallery'),
    path('post-format-quote', blogViews.postFormatQuote, name ='postFormatQuote'),
    path('post-format-standard', blogViews.postFormatStandard, name ='postFormatStandard'),
    path('post-format-video', blogViews.postFormatVideo, name ='postFormatVideo'),

    # pages
    path('aboutus-01', pagesViews.aboutus01, name ='aboutus01'),
    path('aboutus-02', pagesViews.aboutus02, name ='aboutus02'),
    path('academy-gallery', pagesViews.academyGallery, name ='academyGallery'),
    path('admission-guide', pagesViews.admissionGuide, name ='admissionGuide'),
    path('become-teacher', pagesViews.becomeTeacher, name ='becomeTeacher'),
    path('cart', pagesViews.cart, name ='cart'),
    path('contact', pagesViews.contact, name ='contact'),
    path('event-details', pagesViews.eventDetails, name ='eventDetails'),
    path('event-grid', pagesViews.eventGrid, name ='eventGrid'),
    path('event-list', pagesViews.eventList, name ='eventList'),
    path('event-sidebar', pagesViews.eventSidebar, name ='eventSidebar'),
    path('faqs', pagesViews.faqs, name ='faqs'),
    path('instructor', pagesViews.instructor, name ='instructor'),
    path('login', pagesViews.login, name ='login'),
    path('maintenance', pagesViews.maintenance, name ='maintenance'),
    path('my-account', pagesViews.myAccount, name ='myAccount'),
    path('page-error', pagesViews.pageError, name ='pageError'),
    path('privacy-policy', pagesViews.privacyPolicy, name ='privacyPolicy'),
    path('profile', pagesViews.profile, name ='profile'),
    path('shop', pagesViews.shop, name ='shop'),
    path('single-product', pagesViews.singleProduct, name ='singleProduct'),
    path('subscription', pagesViews.subscription, name ='subscription'),
    path('wishlist-2', pagesViews.wishlist2, name ='wishlist2'),
    
    # courses
    path('course-card-2', coursesViews.courseCard2, name ='courseCard2'),
    path('course-card-3', coursesViews.courseCard3, name ='courseCard3'),
    path('course-details', coursesViews.courseDetails, name ='courseDetails'),
    path('course-details-2', coursesViews.courseDetails2, name ='courseDetails2'),
    path('course-details-3', coursesViews.courseDetails3, name ='courseDetails3'),
    path('course-filter-one-open', coursesViews.courseFilterOneOpen, name ='courseFilterOneOpen'),
    path('course-filter-one-toggle', coursesViews.courseFilterOneToggle, name ='courseFilterOneToggle'),
    path('course-filter-two-open', coursesViews.courseFilterTwoOpen, name ='courseFilterTwoOpen'),
    path('course-filter-two-toggle', coursesViews.courseFilterTwoToggle, name ='courseFilterTwoToggle'),
    path('course-masonry', coursesViews.courseMasonry, name ='courseMasonry'),
    path('course-with-sidebar', coursesViews.courseWithSidebar, name ='courseWithSidebar'),
    path('course-with-tab', coursesViews.courseWithTab, name ='courseWithTab'),
    path('course-with-tab-two', coursesViews.courseWithTabTwo, name ='courseWithTabTwo'),
    path('create-course', coursesViews.createCourse, name ='createCourse'),
    path('instruc-tor-course', coursesViews.instructorCourse, name ='instructorCourse'),
    path('lesson', coursesViews.lesson, name ='lesson'),

    # dashboard/Instructor-dashboard
    path('instructor-announcements', dashboardViews.instructorAnnouncements, name ='instructorAnnouncements'),
    path('instructor-assignments', dashboardViews.instructorAssignments, name ='instructorAssignments'),
    path('instructor-dashboard', dashboardViews.instructorDashboard, name ='instructorDashboard'),
    path('instructor-enrolled-courses', dashboardViews.instructorEnrolledCourses, name ='instructorEnrolledCourses'),
    path('instructor-my-quiz-attempts', dashboardViews.instructorMyQuizAttempts, name ='instructorMyQuizAttempts'),
    path('instructor-order-history', dashboardViews.instructorOrderHistory, name ='instructorOrderHistory'),
    path('instructor-profile', dashboardViews.instructorProfile, name ='instructorProfile'),
    path('instructor-quiz-attempts', dashboardViews.instructorQuizAttempts, name ='instructorQuizAttempts'),
    path('instructor-reviews', dashboardViews.instructorReviews, name ='instructorReviews'),
    path('instructor-settings', dashboardViews.instructorSettings, name ='instructorSettings'),
    path('instructor-wishlist', dashboardViews.instructorWishlist, name ='instructorWishlist'),
    
    # dashboard/Student-dashboard
    path('student-dashboard', dashboardViews.studentDashboard, name ='studentDashboard'),
    path('student-enrolled-courses', dashboardViews.studentEnrolledCourses, name ='studentEnrolledCourses'),
    path('student-my-quiz-attempts', dashboardViews.studentMyQuizAttempts, name ='studentMyQuizAttempts'),
    path('student-order-history', dashboardViews.studentOrderHistory, name ='studentOrderHistory'),
    path('student-profile', dashboardViews.studentProfile, name ='studentProfile'),
    path('student-reviews', dashboardViews.studentReviews, name ='studentReviews'),
    path('student-settings', dashboardViews.studentSettings, name ='studentSettings'),
    path('student-wishlist', dashboardViews.studentWishlist, name ='studentWishlist'),
    
    # elements
    path('about', elementsViews.about, name ='about'),
    path('accordion', elementsViews.accordion, name ='accordion'),
    path('advancetab', elementsViews.advancetab, name ='advancetab'),
    path('badge', elementsViews.badge, name ='badge'),
    path('brand', elementsViews.brand, name ='brand'),
    path('button', elementsViews.button, name ='button'),
    path('call-to-action', elementsViews.callToAction, name ='callToAction'),
    path('card', elementsViews.card, name ='card'),
    path('category', elementsViews.category, name ='category'),
    path('counterup', elementsViews.counterup, name ='counterup'),
    path('gallery', elementsViews.gallery, name ='gallery'),
    path('header', elementsViews.header, name ='header'),
    path('instagram', elementsViews.instagram, name ='instagram'),
    path('listStyle', elementsViews.listStyle, name ='listStyle'),
    path('newsletter', elementsViews.newsletter, name ='newsletter'),
    path('pricing', elementsViews.pricing, name ='pricing'),
    path('progressbar', elementsViews.progressbar, name ='progressbar'),
    path('search', elementsViews.search, name ='search'),
    path('service', elementsViews.service, name ='service'),
    path('social', elementsViews.social, name ='social'),
    path('split', elementsViews.split, name ='split'),
    path('style-guide', elementsViews.styleGuide, name ='styleGuide'),
    path('team', elementsViews.team, name ='team'),
    path('testimonial', elementsViews.testimonial, name ='testimonial'),
    
    # main
    path('all-questions', mainViews.allQuestions, name ='allQuestions'),
    path('elements', mainViews.elements, name ='elements'),
    path('header-layout', mainViews.headerLayout, name ='headerLayout'),
    path('lesson-assignments', mainViews.lessonAssignments, name ='lessonAssignments'),
    path('lesson-assignments-submit', mainViews.lessonAssignmentsSubmit, name ='lessonAssignmentsSubmit'),
    path('lesson-intro', mainViews.lessonIntro, name ='lessonIntro'),
    path('lesson-quiz', mainViews.lessonQuiz, name ='lessonQuiz'),
    path('lesson-quiz-result', mainViews.lessonQuizResult, name ='lessonQuizResult'),
    path('modal', mainViews.modal, name ='modal'),
    path('pagination-quiz', mainViews.paginationQuiz, name ='paginationQuiz'),
    path('purchase-guide', mainViews.purchaseGuide, name ='purchaseGuide'),
    path('questions-types', mainViews.questionsTypes, name ='questionsTypes'),
    path('quiz-with-custom-timer', mainViews.quizWithCustomTimer, name ='quizWithCustomTimer'),
    path('quiz-with-point', mainViews.quizWithPoint, name ='quizWithPoint'),
    path('sample-page-one', mainViews.samplePageOne, name ='samplePageOne'),
    path('sample-page-two', mainViews.samplePageTwo, name ='samplePageTwo'),
    path('single-question', mainViews.singleQuestion, name ='singleQuestion'),

]
