# Generated by Django 5.2.1 on 2025-09-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(default=32, max_length=100),
            preserve_default=False,
        ),
    ]
