# Generated by Django 5.2.1 on 2025-07-17 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_departments'),
        ('degreeLevel', '0001_initial'),
        ('department', '0007_remove_department_degree_level_delete_degreelevel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='degreelevel',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='degreelevel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AddField(
            model_name='degreelevel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='degree_level/images/'),
        ),
        migrations.AddField(
            model_name='degreelevel',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='degreelevel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='degree_level/images/thumbnails/'),
        ),
        migrations.AddField(
            model_name='degreelevel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
