# Generated by Django 5.2.1 on 2025-08-11 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degreeLevel', '0002_degreelevel_courses_degreelevel_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreelevel',
            name='user',
        ),
        migrations.AddField(
            model_name='degreelevel',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students_degree_level', to=settings.AUTH_USER_MODEL),
        ),
    ]
