from .quiz import *
from .lesson import *
from .course import *
from .college import *
from .department import *
from .teacher import *
from .student import *
from .payment import *
from .registration import *
from .dashboard import *
from .other import *
