# Generated by Django 5.1.6 on 2026-01-23 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('subscription_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='سعر الاشتراك في القسم', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='department/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='department/images/thumbnails/')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_admin', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='college.college')),
            ],
        ),
    ]
