# Generated by Django 5.2.1 on 2025-06-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_college_department_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
