# Generated by Django 5.2.1 on 2025-06-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_degreelevel_created_at_degreelevel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreelevel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
