# Generated by Django 5.2.1 on 2025-07-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_department_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='degree_level',
        ),
        migrations.DeleteModel(
            name='DegreeLevel',
        ),
    ]
