# Generated by Django 5.2.1 on 2025-08-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_remove_department_degree_level_delete_degreelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='سعر الاشتراك في القسم', max_digits=10),
        ),
    ]
